version: 0.2
phases:
  install:
    commands:
        - apt-get update
        - sudo apt install -y apache2
        - sudo service apache2 start
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:

artifacts:
  files: 
    - '**/*'