version: 0.1
phases:
  install:
    commands:
        - apt-get update
        - sudo apt install -y apache2
        - sudo service apache2 start
        - chkconfig apache2 on
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
artifacts:
  files:
  discard-paths: yes
cache:
  paths: